### ISSUE TITLE
Installation details are not clear

### ISSUE THREAD

**Issue by TFesmire** [shadiakiki1986/dbxcli-extras#2]
I installed dbxcli-extras, but it's not clear how to point it to dbxcli. As you can see below, dbxcli-extras can't find the dbxcli executable even though they are both in the path:

```
testuser@test:~$ ll .local/bin/dbxcli*
-rwxrwxr-x 1 testuser testuser 8665216 Oct 29 19:26 .local/bin/dbxcli*
-rwxrwxr-x 1 testuser testuser     214 Oct 29 19:20 .local/bin/dbxcli_extras*
```
```
testuser@test:~$ dbxcli
Use dbxcli to quickly interact with your Dropbox, upload/download files,
manage your team and more. It is easy, scriptable and works on all platforms!

Usage:
  dbxcli [command]
...
```
```
testuser@test:~$ dbxcli_extras getr Pricing test/Pricing
Traceback (most recent call last):
  File "/home/testuser/.local/bin/dbxcli_extras", line 8, in <module>
    sys.exit(cli())
  File "/home/testuser/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/testuser/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/testuser/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/testuser/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/testuser/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/testuser/.local/lib/python3.9/site-packages/dbxcli_extras/cli.py", line 34, in getr
    dcg.getr(dbxdir, localdir)
  File "/home/testuser/.local/lib/python3.9/site-packages/dbxcli_extras/getr.py", line 43, in getr
    for obj_isdir, obj_name in self.dbxapi.ls_dir(remote):
  File "/home/testuser/.local/lib/python3.9/site-packages/dbxcli_extras/dropbox_api.py", line 50, in ls_dir
    proc = self.my_run(dlcmd, stdout=subprocess.PIPE)
  File "/home/testuser/.local/lib/python3.9/site-packages/dbxcli_extras/dropbox_api.py", line 14, in my_run
    return subprocess.run(cx, stdout=stdout, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dbxcli'
```
```testuser@test:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:~/.local/bin/
```

What's the problem with the configuration and how do I fix it?

**Comment by shadiakiki1986** [comment]
Could you run with higher verbosity to see some logs? ie
```
dbxcli_extras getr --verbosity=2 Pricing test/Pricing
```
